logging:
  level:
    com:
      xzone: debug
spring:
  datasource:
    username: zhixuehui
    password: zhiXuehui_1234
    url: jdbc:mysql://localhost:23306/zhixuehui?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
